-- AlterTable
ALTER TABLE `bookings` MODIFY `status` ENUM('PENDING_HOST_APPROVAL', 'PENDING_PAYMENT', 'CHECK_IN_PENDING', 'DISPUTED', 'DISPUTE_RESOLVED_FOR_HOST', 'COMPLETED', 'REJECTED', 'CANCELED', 'CANCELLED_BY_GUEST', 'CANCELLED_BY_HOST', 'CANCELLED_AFTER_DISPUTE', 'REFUNDED', 'EXPIRED') NOT NULL DEFAULT 'PENDING_HOST_APPROVAL';
