-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('USER_VERIFICATION_APPROVED', 'USER_VERIFICATION_REJECTED', 'USER_VERIFICATION_NEEDS_CHANGES', 'LISTING_VERIFICATION_APPROVED', 'LISTING_VERIFICATION_REJECTED', 'LISTING_VERIFICATION_NEEDS_CHANGES', 'BOOKING_REQUESTED', 'BOOKING_APPROVED', 'BOOKING_REJECTED', 'PAYMENT_REQUIRED', 'PAYMENT_CONFIRMED') NOT NULL;
