export const AMENITY_OPTIONS = [
  { key: "wifi", label: "واي فاي" },
  { key: "air_conditioning", label: "تكييف" },
  { key: "microwave", label: "ميكروويف" },
  { key: "dishwasher", label: "غسالة أطباق" },
  { key: "garden", label: "حديقة" },
  { key: "tv", label: "تلفاز" },
  { key: "elevator", label: "مصعد" },
  { key: "parking", label: "موقف سيارات" },
  { key: "balcony", label: "شرفة" },
  { key: "hot_water", label: "مياه ساخنة" },
  { key: "security", label: "أمن وحراسة" },
  { key: "cctv", label: "كاميرات مراقبة" },
  { key: "concierge", label: "بواب" },
  { key: "workspace", label: "مكتب دراسة" },
  { key: "wardrobe", label: "خزائن ملابس" },
  { key: "cleaning_service", label: "خدمة تنظيف" },
  { key: "high_speed_internet", label: "إنترنت عالي السرعة" },
];
