-- Add reservation lock support after owner approval.
ALTER TABLE `bookings`
  ADD COLUMN `approvedAt` DATETIME(3) NULL;

ALTER TABLE `listings`
  MODIFY `status` ENUM('ACTIVE', 'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'RESERVED', 'REJECTED', 'INACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'DRAFT';

ALTER TABLE `bookings`
  MODIFY `status` ENUM('PENDING_HOST_APPROVAL', 'PENDING_PAYMENT', 'CHECK_IN_PENDING', 'DISPUTED', 'COMPLETED', 'REJECTED', 'CANCELED', 'CANCELLED_BY_GUEST', 'CANCELLED_BY_HOST', 'REFUNDED') NOT NULL DEFAULT 'PENDING_HOST_APPROVAL';
